# uploader.py
# This file is licensed under the MIT License
# See the LICENSE file in the project root for more information

import json
import logging
from typing import Any, Dict, List, Tuple

from pyzotero import zotero
from ratelimit import limits, sleep_and_retry
from tenacity import retry, stop_after_attempt, wait_exponential

from paper_scout.core.config import configs
from paper_scout.core.constant import ZOTERO_PERIOD, ZOTERO_RATE_LIMIT
from paper_scout.database.model import Paper, Status


# 设置日志记录
logger = logging.getLogger(__name__)


class ZoteroUploader:
    """Zotero上传器"""

    def __init__(self) -> None:
        # 创建Zotero客户端
        self.zot = zotero.Zotero(
            library_id=configs.zotero_user_id,
            library_type="user",
            api_key=configs.zotero_api_key
        )

    def upload_all(self, papers: List[Paper]) -> Dict[Status, List[Paper]]:
        """批量上传论文"""
        if not papers:
            logger.warning(f"Papers not provided to upload")
            return {}
        logger.info(f"Uploading {len(papers)} papers to Zotero...")
        all_papers = {
            Status.COMPLETED: [],
            Status.UPLOAD_FAILED: []
        }
        # 批量上传
        for i in range(0, len(papers), configs.zotero_batch_limit):
            logger.info(f"Uploading {i} to {i + configs.zotero_batch_limit} papers...")
            batch_papers = papers[i:i + configs.zotero_batch_limit]
            uploaded, failed = self._batch_upload(papers=batch_papers)
            all_papers[Status.COMPLETED].extend(uploaded)
            if failed:
                all_papers[Status.UPLOAD_FAILED].extend(failed)
                logger.warning(f"Failed to upload {len(failed)} papers")
        if not all_papers[Status.COMPLETED]:
            logger.error(f"Failed to upload any paper")
            return all_papers
        logger.info(f"{len(all_papers[Status.COMPLETED])} papers uploaded successfully")
        return all_papers

    def _batch_upload(self, papers: List[Paper]) -> Tuple[List[Paper], List[Paper]]:
        """批量上传单批次论文"""
        logger.info(f"Uploading {len(papers)} papers to Zotero...")
        templates = []
        for paper in papers:
            templates.append(self._create_template(paper=paper))
        try:
            response = self._create_items(templates=templates)
        except Exception as e:
            logger.error(f"Failed to upload {len(papers)} papers")
            logger.debug(f"Exception: {e}")
            return [], papers
        # 解析上传结果
        uploaded_response = response.get("successful", [])
        failed_response = response.get("failed", [])
        # 解析成功上传的论文
        uploaded_papers = []
        failed_papers = []
        for idx, paper in enumerate(papers):
            idx_str = str(idx)
            if idx_str in uploaded_response:
                paper.zotero_key = uploaded_response[idx_str].get("key")
                uploaded_papers.append(paper)
            else:
                failed_papers.append(paper)
                error = failed_response.get(idx_str, "Unknown Error")
                logger.error(f"Failed to upload paper with DOI: {paper.doi}")
                logger.debug(f"Error: {error}")
        return uploaded_papers, failed_papers

    def _create_template(self, paper: Paper) -> Dict[str, str]:
        """创建Zotero上传模板"""
        template = self.zot.item_template("journalArticle")
        # 添加DOI
        if paper.doi and not paper.doi.startswith("pseudo_doi:"):
            template["DOI"] = paper.doi
        # 添加标题
        template["title"] = paper.title
        # 添加摘要
        template["abstractNote"] = paper.abstract
        # 添加额外信息
        extra_info = (
            f"中文标题: {paper.title_cn}\n\n"
            f"中文摘要: {paper.abstract_cn}\n\n"
            f"筛选理由: {paper.relevance_reason}\n\n"
            "---\n\n"
            "Generated by: PaperScout\n"
            f"AI Support: {configs.llm_base_url}/{configs.llm_model}\n"
            "Data Sources: dblp, Crossref, Semantic Scholar, OpenAlex\n"
        )
        template["extra"] = extra_info
        # 反序列化标签
        try:
            tags_list = json.loads(paper.tags_json) if paper.tags_json else []
            template["tags"] = [{"tag": tag} for tag in tags_list]
        except json.JSONDecodeError:
            logger.warning(f"Failed to parse tags for paper with DOI: {paper.doi}")
        # 添加集合
        template["collections"] = [configs.zotero_inbox_key]
        return template

    @retry(stop=stop_after_attempt(configs.max_retries),
           wait=wait_exponential(multiplier=2, min=2, max=configs.request_timeout))
    @sleep_and_retry
    @limits(calls=ZOTERO_RATE_LIMIT, period=ZOTERO_PERIOD)
    def _create_items(self, templates: List[Dict[str, str]]) -> Dict[str, Any]:
        """创建Zotero项目"""
        return self.zot.create_items(templates)
